version: "3.8"
services:
  app:
    container_name: ${PROJECT}-app
    build: ./docker/php
    volumes:
      - "./cakephp/:/app:cached"
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    working_dir: "/app"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    tty: true
  web:
    container_name: ${PROJECT}-web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      - 8000:80
    volumes:
      # - ./public:/app/public:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    environment:
      - TZ=${TZ}
    tty: true