version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - "./:/app:cached"
    working_dir: "/app"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    tty: true